version: '3.3'
services:            
    action:
        build:
            context: .
            dockerfile: Dockerfile
            labels:
                com.github.actions.name: "NPM Publish"
                com.github.actions.description: "Publish an npm package"
                com.github.actions.icon: "mic"
                com.github.actions.color: "purple"
                repository: "http://github.com/chimpwizards-pipeline/npm-publish"
                homepage: "http://github.com/marketplace/chimpwizards"
                maintainer: "ndru@chimpwizard.com"
        image: 'chimpwizards/pipeline-npm-publish'
